import { Inter } from "next/font/google";
import { DashboardTopNav, MobileDashNav, SideNavAdmin } from "@/components";
import { AuthWrapper } from "@/components/AuthModals";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <div className={` dashboard ${inter.className}`}>
      <div className="top-nav" >
        <DashboardTopNav />
      </div>
      <div className="dashboard-body" >
        <div className="side-nav-cont" >
          <SideNavAdmin />
        </div>
        <MobileDashNav />
        <div className="dashboard-page" >
          {children}
        </div>
      </div>
          
    </div>
  );
}
